[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson @ ^7.4.2
  knolleary/PubSubClient @ ^2.8
  adafruit/Adafruit SHT4x Library @ ^1.0.5
  adafruit/Adafruit BusIO @ ^1.17.2
  bodmer/TFT_eSPI @ ^2.5.43
  lvgl/lvgl @ 9.5.0

build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DLV_CONF_INCLUDE_SIMPLE
  -Iinclude
  -DUSER_SETUP_LOADED=1
  -DUSE_HSPI_PORT=1
  -DILI9341_2_DRIVER=1
  -DTFT_INVERSION_ON=1
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DTFT_MISO=12
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DTFT_CS=15
  -DTFT_DC=2
  -DTFT_RST=-1
  -DTFT_BL=21
  -DTFT_BACKLIGHT_ON=HIGH
  -DTFT_RGB_ORDER=TFT_RGB
  -DTOUCH_CS=33
  -DSPI_FREQUENCY=40000000
  -DSPI_READ_FREQUENCY=16000000
  -DSPI_TOUCH_FREQUENCY=2500000
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
  -DLOAD_FONT4=1
  -DLOAD_FONT6=1
  -DLOAD_FONT7=1
  -DLOAD_FONT8=1
  -DLOAD_GFXFF=1
  -DSMOOTH_FONT=1
