[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^7.4.2
  knolleary/PubSubClient @ ^2.8
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit SHT4x Library @ ^1.0.5
  adafruit/Adafruit BusIO @ ^1.17.2
build_flags =
  -DCORE_DEBUG_LEVEL=1
